version: "2.4"

services:
    momandpops:
        image: <accountID>.dkr.ecr.us-east-2.amazonaws.com/momandpops:latest
        container_name: momandpops
        pids_limit: 50
        ports:
            - "8081:80"
        restart: unless-stopped
    omniflags:
        image: <accountID>.dkr.ecr.us-east-2.amazonaws.com/omniflags:latest
        container_name: omniflags
        pids_limit: 50
        ports:
            - "8080:80"
        restart: unless-stopped
    watchtower:
        image: containrrr/watchtower
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /root/.docker/config.json:/config.json
        command: --interval 180